language: python
python:
  # - "2.7"
  - "3.4"
# command to install dependencies
install:
  - "make reqs"
  - "pip install coveralls"
# command to run tests
script: make unit
after_success: coveralls
